name: "Push Docs Check"
on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - uses: ammaraskar/sphinx-action@master
        # with:
      - name: Generating documentation
        run: make html
        working-directory: "tests_app"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tests_app/build/html
          force_orphan: true
          
