name: "Deploy on gh-pages"
on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: "Select the deployment environment"
                options:
                    - deploy-gh-pages

jobs:
    deploy-gh-pages:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./DAW/RA6/Pagina-noBack-noDocs/src
                  force_orphan: true
